/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: InternationalizedArrayString;
  role?: InternationalizedArrayString;
  company?: InternationalizedArrayString;
  quote: InternationalizedArrayText;
  avatar?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type InternationalizedArrayText = Array<{
  _key: string;
} & InternationalizedArrayTextValue>;

export type InternationalizedArrayString = Array<{
  _key: string;
} & InternationalizedArrayStringValue>;

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: InternationalizedArrayString;
  slug: Slug;
  category: "exterior" | "interior" | "construction" | "finishing" | "renovation";
  location?: InternationalizedArrayString;
  isFeatured?: boolean;
  featuredImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type InternationalizedArrayTextValue = {
  _type: "internationalizedArrayTextValue";
  value?: string;
};

export type InternationalizedArrayStringValue = {
  _type: "internationalizedArrayStringValue";
  value?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Testimonial | SanityImageCrop | SanityImageHotspot | InternationalizedArrayText | InternationalizedArrayString | Project | Slug | InternationalizedArrayTextValue | InternationalizedArrayStringValue | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: sanity/lib/queries.ts
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial"] | order(_createdAt desc) {    _id,    "name": coalesce(name[_key == $lang][0].value, name[_key == "en"][0].value, ""),    "role": coalesce(role[_key == $lang][0].value, role[_key == "en"][0].value),    "company": coalesce(company[_key == $lang][0].value, company[_key == "en"][0].value),    "quote": coalesce(quote[_key == $lang][0].value, quote[_key == "en"][0].value, ""),    "avatar": avatar.asset->url  }
export type TESTIMONIALS_QUERYResult = Array<{
  _id: string;
  name: string | "";
  role: string | null;
  company: string | null;
  quote: string | "";
  avatar: string | null;
}>;
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"     && defined(slug.current)    && select(      defined($category) && $category != "" => category == $category,      true    )    && select(      defined($isFeatured) => isFeatured == $isFeatured,      true    )  ] | order(_createdAt desc) {    _id,    "title": coalesce(title[_key == $lang][0].value, title[_key == "en"][0].value, "Untitled"),    slug,    category,    "location": coalesce(location[_key == $lang][0].value, location[_key == "en"][0].value),    isFeatured,    "featuredImage": featuredImage.asset->{      url,      "width": metadata.dimensions.width,      "height": metadata.dimensions.height,      "lqip": metadata.lqip    }  }
export type PROJECTS_QUERYResult = Array<{
  _id: string;
  title: string | "Untitled";
  slug: Slug;
  category: "construction" | "exterior" | "finishing" | "interior" | "renovation";
  location: string | null;
  isFeatured: boolean | null;
  featuredImage: {
    url: string | null;
    width: number | null;
    height: number | null;
    lqip: string | null;
  } | null;
}>;
// Variable: FEATURED_PROJECTS_QUERY
// Query: *[_type == "project" && defined(slug.current) && isFeatured == true] | order(_createdAt desc) {    _id,    "title": coalesce(title[_key == $lang][0].value, title[_key == "en"][0].value, "Untitled"),    slug,    category,    "featuredImage": featuredImage.asset->{      url,      "width": metadata.dimensions.width,      "height": metadata.dimensions.height,      "lqip": metadata.lqip    }  }
export type FEATURED_PROJECTS_QUERYResult = Array<{
  _id: string;
  title: string | "Untitled";
  slug: Slug;
  category: "construction" | "exterior" | "finishing" | "interior" | "renovation";
  featuredImage: {
    url: string | null;
    width: number | null;
    height: number | null;
    lqip: string | null;
  } | null;
}>;
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0] {    _id,    "title": coalesce(title[_key == $lang][0].value, title[_key == "en"][0].value, "Untitled"),    slug,    category,    "location": coalesce(location[_key == $lang][0].value, location[_key == "en"][0].value),    area,    year,    clientName,    description,    "featuredImage": featuredImage.asset->{      url,      "width": metadata.dimensions.width,      "height": metadata.dimensions.height,      "lqip": metadata.lqip    }  }
export type PROJECT_QUERYResult = {
  _id: string;
  title: string | "Untitled";
  slug: Slug;
  category: "construction" | "exterior" | "finishing" | "interior" | "renovation";
  location: string | null;
  area: null;
  year: null;
  clientName: null;
  description: null;
  featuredImage: {
    url: string | null;
    width: number | null;
    height: number | null;
    lqip: string | null;
  } | null;
} | null;
// Variable: PROJECTS_INITIAL_QUERY
// Query: *[_type == "project"     && defined(slug.current)    && category == $category  ] | order(_createdAt desc) [0...6] {    _id,    _createdAt,    "title": coalesce(title[_key == $lang][0].value, title[_key == "en"][0].value, "Untitled"),    slug,    category,    "location": coalesce(location[_key == $lang][0].value, location[_key == "en"][0].value),    "featuredImage": featuredImage.asset->{      url,      "width": metadata.dimensions.width,      "height": metadata.dimensions.height,      "lqip": metadata.lqip    }  }
export type PROJECTS_INITIAL_QUERYResult = Array<{
  _id: string;
  _createdAt: string;
  title: string | "Untitled";
  slug: Slug;
  category: "construction" | "exterior" | "finishing" | "interior" | "renovation";
  location: string | null;
  featuredImage: {
    url: string | null;
    width: number | null;
    height: number | null;
    lqip: string | null;
  } | null;
}>;
// Variable: PROJECTS_CURSOR_QUERY
// Query: *[_type == "project"     && defined(slug.current)    && category == $category    && (      _createdAt < $lastCreatedAt      || (_createdAt == $lastCreatedAt && _id > $lastId)    )  ] | order(_createdAt desc) [0...6] {    _id,    _createdAt,    "title": coalesce(title[_key == $lang][0].value, title[_key == "en"][0].value, "Untitled"),    slug,    category,    "location": coalesce(location[_key == $lang][0].value, location[_key == "en"][0].value),    "featuredImage": featuredImage.asset->{      url,      "width": metadata.dimensions.width,      "height": metadata.dimensions.height,      "lqip": metadata.lqip    }  }
export type PROJECTS_CURSOR_QUERYResult = Array<{
  _id: string;
  _createdAt: string;
  title: string | "Untitled";
  slug: Slug;
  category: "construction" | "exterior" | "finishing" | "interior" | "renovation";
  location: string | null;
  featuredImage: {
    url: string | null;
    width: number | null;
    height: number | null;
    lqip: string | null;
  } | null;
}>;
// Variable: PROJECTS_COUNT_QUERY
// Query: count(*[_type == "project" && defined(slug.current) && category == $category])
export type PROJECTS_COUNT_QUERYResult = number;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"testimonial\"] | order(_createdAt desc) {\n    _id,\n    \"name\": coalesce(name[_key == $lang][0].value, name[_key == \"en\"][0].value, \"\"),\n    \"role\": coalesce(role[_key == $lang][0].value, role[_key == \"en\"][0].value),\n    \"company\": coalesce(company[_key == $lang][0].value, company[_key == \"en\"][0].value),\n    \"quote\": coalesce(quote[_key == $lang][0].value, quote[_key == \"en\"][0].value, \"\"),\n    \"avatar\": avatar.asset->url\n  }\n": TESTIMONIALS_QUERYResult;
    "\n  *[_type == \"project\" \n    && defined(slug.current)\n    && select(\n      defined($category) && $category != \"\" => category == $category,\n      true\n    )\n    && select(\n      defined($isFeatured) => isFeatured == $isFeatured,\n      true\n    )\n  ] | order(_createdAt desc) {\n    _id,\n    \"title\": coalesce(title[_key == $lang][0].value, title[_key == \"en\"][0].value, \"Untitled\"),\n    slug,\n    category,\n    \"location\": coalesce(location[_key == $lang][0].value, location[_key == \"en\"][0].value),\n    isFeatured,\n    \"featuredImage\": featuredImage.asset->{\n      url,\n      \"width\": metadata.dimensions.width,\n      \"height\": metadata.dimensions.height,\n      \"lqip\": metadata.lqip\n    }\n  }\n": PROJECTS_QUERYResult;
    "\n  *[_type == \"project\" && defined(slug.current) && isFeatured == true] | order(_createdAt desc) {\n    _id,\n    \"title\": coalesce(title[_key == $lang][0].value, title[_key == \"en\"][0].value, \"Untitled\"),\n    slug,\n    category,\n    \"featuredImage\": featuredImage.asset->{\n      url,\n      \"width\": metadata.dimensions.width,\n      \"height\": metadata.dimensions.height,\n      \"lqip\": metadata.lqip\n    }\n  }\n": FEATURED_PROJECTS_QUERYResult;
    "\n  *[_type == \"project\" && slug.current == $slug][0] {\n    _id,\n    \"title\": coalesce(title[_key == $lang][0].value, title[_key == \"en\"][0].value, \"Untitled\"),\n    slug,\n    category,\n    \"location\": coalesce(location[_key == $lang][0].value, location[_key == \"en\"][0].value),\n    area,\n    year,\n    clientName,\n    description,\n    \"featuredImage\": featuredImage.asset->{\n      url,\n      \"width\": metadata.dimensions.width,\n      \"height\": metadata.dimensions.height,\n      \"lqip\": metadata.lqip\n    }\n  }\n": PROJECT_QUERYResult;
    "\n  *[_type == \"project\" \n    && defined(slug.current)\n    && category == $category\n  ] | order(_createdAt desc) [0...6] {\n    _id,\n    _createdAt,\n    \"title\": coalesce(title[_key == $lang][0].value, title[_key == \"en\"][0].value, \"Untitled\"),\n    slug,\n    category,\n    \"location\": coalesce(location[_key == $lang][0].value, location[_key == \"en\"][0].value),\n    \"featuredImage\": featuredImage.asset->{\n      url,\n      \"width\": metadata.dimensions.width,\n      \"height\": metadata.dimensions.height,\n      \"lqip\": metadata.lqip\n    }\n  }\n": PROJECTS_INITIAL_QUERYResult;
    "\n  *[_type == \"project\" \n    && defined(slug.current)\n    && category == $category\n    && (\n      _createdAt < $lastCreatedAt\n      || (_createdAt == $lastCreatedAt && _id > $lastId)\n    )\n  ] | order(_createdAt desc) [0...6] {\n    _id,\n    _createdAt,\n    \"title\": coalesce(title[_key == $lang][0].value, title[_key == \"en\"][0].value, \"Untitled\"),\n    slug,\n    category,\n    \"location\": coalesce(location[_key == $lang][0].value, location[_key == \"en\"][0].value),\n    \"featuredImage\": featuredImage.asset->{\n      url,\n      \"width\": metadata.dimensions.width,\n      \"height\": metadata.dimensions.height,\n      \"lqip\": metadata.lqip\n    }\n  }\n": PROJECTS_CURSOR_QUERYResult;
    "\n  count(*[_type == \"project\" && defined(slug.current) && category == $category])\n": PROJECTS_COUNT_QUERYResult;
  }
}
